apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: marammanai/user-service:latest # 🔁 Remplace par ton image Docker
          ports:
            - containerPort: 8089 # correspond au server.port défini dans application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089          # Ce que Kubernetes écoute dans le cluster
      targetPort: 8089    # Ce que le conteneur expose
#      nodePort: 30091     # Port accessible depuis l’extérieur (VM, navigateur)
